### PR TITLE
Remove the broken Perl script to download Gurobi

### PR DESCRIPTION
**Pull request by david-german-tri**
No longer works thanks to CSRF protection on gurobi.com.  While this could conceivably be fixed, I think it's not worth it, because any solution would be brittle to future changes on Gurobi's end.  Downloading the .tar.gz oneself is not much more burdensome than interacting with the automation anyway.

Update the README accordingly.

@jamiesnape FYI

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/gurobi/12)

### CODE REVIEW

**Comment by jamiesnape** [comment]
> While this could conceivably be fixed,

Hope not. We are basically doing CSRF.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW8v5xC2qCYF7LX5CgE:-KW8v5xC2qCYF7LX5CgF:bcxy0z7) ([raw file](https://github.com/robotlocomotion/gurobi/blob/e9a7f6fb027b548185ca49dc9157f3717eaace4b/README.md#L20)):*
> ```Markdown
> All Platforms
> 
> Download `gurobi6.0.5_linux64.tar.gz` from
> ```

Move to Debian/Ubuntu. Replace with `gurobi6.0.5a_mac64.pkg` for macOS / OS X.

---

*[README.md, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW8vNBbNC_uHzYkRIjg:-KW8vNBbNC_uHzYkRIjh:b40nr0w) ([raw file](https://github.com/robotlocomotion/gurobi/blob/e9a7f6fb027b548185ca49dc9157f3717eaace4b/README.md#L21)):*
> ```Markdown
> 
> Download `gurobi6.0.5_linux64.tar.gz` from
> <http://www.gurobi.com/downloads/download-center>. Set the `GUROBI_DISTRO`
> ```

`https`

---

*[README.md, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW8vbLmFmpaFSH7pRpE:-KW8vZbZquPgb7qB9ENP:bt023wp) ([raw file](https://github.com/robotlocomotion/gurobi/blob/e9a7f6fb027b548185ca49dc9157f3717eaace4b/README.md#L22)):*
> ```Markdown
> Download `gurobi6.0.5_linux64.tar.gz` from
> <http://www.gurobi.com/downloads/download-center>. Set the `GUROBI_DISTRO`
> environment variable to the path to the downloaded file.  Then:
> ```

absolute path

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-:-KW8uBqU4Qg-_zuTRObk:b-bhspah)*

**Comment by jamiesnape** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by david-german-tri** [comment]
> Hope not. We are basically doing CSRF.

Eh?  This script is acting as a user-agent, not a third party website, so all things should be possible with sufficient brittle hacking, right?   Not that I want to grep Gurobi's HTML for the CSRF token.  Just saying we could.

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 20 at r1](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW8v5xC2qCYF7LX5CgE:-KW8zB4opB1s3G736Po6:b-896fix) ([raw file](https://github.com/robotlocomotion/gurobi/blob/e9a7f6fb027b548185ca49dc9157f3717eaace4b/README.md#L20)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> Move to Debian/Ubuntu. Replace with `gurobi6.0.5a_mac64.pkg` for macOS / OS X.
</details>
Done.

---

*[README.md, line 21 at r1](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW8vNBbNC_uHzYkRIjg:-KW8zBQ4XwAR8A8buGbA:b-896fix) ([raw file](https://github.com/robotlocomotion/gurobi/blob/e9a7f6fb027b548185ca49dc9157f3717eaace4b/README.md#L21)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> `https`
</details>
Done.

---

*[README.md, line 22 at r1](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW8vbLmFmpaFSH7pRpE:-KW8zBmzyiqQ5qgB1ZTT:b-896fix) ([raw file](https://github.com/robotlocomotion/gurobi/blob/e9a7f6fb027b548185ca49dc9157f3717eaace4b/README.md#L22)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> absolute path
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-:-KW8tx_ttLgueA8PSsT3:bjkr77p)*

**Comment by jamiesnape** [comment]
Depends how you define CSRF. But in any case, you are correct that it would not be worth fixing.

:lgtm: 

---

Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-:-KW8ziB1ryx9y1ZqIYZF:br67fc3)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CMakeLists.txt, line 75 at r3](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW99oUTDgwdyxUhEAQA:-KW99oUTDgwdyxUhEAQB:b-x80avr) ([raw file](https://github.com/robotlocomotion/gurobi/blob/eb21132665af897fcc875dd1581958d6ddbe0bec/CMakeLists.txt#L75)):*
> ```CMake
> 
> if(NOT GUROBI_DISTRO OR NOT EXISTS "${GUROBI_DISTRO}" OR IS_DIRECTORY "${GUROBI_DISTRO}")
>   message(FATAL_ERROR "Please download the Gurobi 6.0.5 archive (.tar.gz) and set \$GUROBI_DISTRO to its location.")
> ```

I missed this before. Replace 6.0.5 with ${PROJECT_VERSION}.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 75 at r3](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KW99oUTDgwdyxUhEAQA:-KW9CCsCTQuq0G5sDfkS:b-896fix) ([raw file](https://github.com/robotlocomotion/gurobi/blob/eb21132665af897fcc875dd1581958d6ddbe0bec/CMakeLists.txt#L75)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> I missed this before. Replace 6.0.5 with ${PROJECT_VERSION}.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by jamiesnape** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-:-KW9OhHCD_5xMrKvcIRX:bnfp4nl)*

**Comment by RussTedrake** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CMakeLists.txt, line 75 at r4](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KWAkswBa2lRuIlmp_sQ:-KWAkswBa2lRuIlmp_sR:b-exd2ac) ([raw file](https://github.com/robotlocomotion/gurobi/blob/9b708640be1b052477626925ddd9654d305a1388/CMakeLists.txt#L75)):*
> ```CMake
> 
> if(NOT GUROBI_DISTRO OR NOT EXISTS "${GUROBI_DISTRO}" OR IS_DIRECTORY "${GUROBI_DISTRO}")
>   message(FATAL_ERROR "Please download the Gurobi ${PROJECT_VERSION} archive (.tar.gz) and set \$GUROBI_DISTRO to its location.")
> ```

can we direct them to the README for the instructions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by jamiesnape** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 75 at r4](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KWAkswBa2lRuIlmp_sQ:-KWB6c7tikfzy47z8vFE:bfqyxq9) ([raw file](https://github.com/robotlocomotion/gurobi/blob/9b708640be1b052477626925ddd9654d305a1388/CMakeLists.txt#L75)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary>
> can we direct them to the README for the instructions?
</details>
We should point them to a URL: https://git.io/vXVsE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by david-german-tri** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 75 at r4](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12#-KWAkswBa2lRuIlmp_sQ:-KWE0Ca1IDEBwZWe0NGK:b-896fix) ([raw file](https://github.com/robotlocomotion/gurobi/blob/9b708640be1b052477626925ddd9654d305a1388/CMakeLists.txt#L75)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary>
> We should point them to a URL: https://git.io/vXVsE.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by RussTedrake** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Comment by jamiesnape** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/12)*

**Pull request merged**
