### PR TITLE
Really fix pkg-config file

### PR DESCRIPTION
**Pull request by jamiesnape**
PTAL @david-german-tri.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/gurobi/14)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Pinging @david-german-tri.

**Comment by david-german-tri** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/14#-:-KWjJyoCTriUOZwhS9cI:bnfp4nl)*

**Comment by jamiesnape** [comment]
Please merge this and I will PR an updated SHA across at drake.

**Comment by jamiesnape** [comment]
RobotLocomotion/drake#4167.

**Pull request merged**
