### PR TITLE
Updated the SHA256 for Gurobi 6.0.5 for OSX

### PR DESCRIPTION
**Pull request by pvarin**
The current SHA256 for Gurobi 6.0.5 on OSX is wrong. This is a small fix.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/gurobi/16)

### CODE REVIEW

**Comment by jamiesnape** [comment]
I am seeing the following:
```
$ shasum -a 256 gurobi6.0.5a_mac64.pkg 
63a6e5b8734b14ad54f2ccc47620e1bd8bbea02a66f88a7fd969278644b8d125  gurobi6.0.5a_mac64.pkg
```

**Comment by pvarin** [comment]
Hm, I'm seeing this:
```
shasum -a 256 gurobi6.0.5_mac64.pkg
119b2c5bb360a19d6d8580653b4b39977d0254a80c34d8f8c07055cd0af5a3e2  gurobi6.0.5_mac64.pkg
```
It looks like our files have different names, where did you get yours from? Mine is from https://www.gurobi.com/downloads/gurobi-optimizer

**Comment by jamiesnape** [comment]
We used to have an interactive downloader: https://github.com/RobotLocomotion/gurobi/blob/fbbdbbc0152ddb37df209d221aff37448b8ff29f/download_gurobi.pl#L92

**Comment by jamiesnape** [comment]
Looks like something changed. I will need to update the version that we store on our VM images before we can update the SHA. I will do so tomorrow.

**Comment by pvarin** [comment]
Why would they have different hashes? If you download Gurobi manually, per the new instructions, do you get the same hash that I do?

I feel like since the installation instructions changed we should either support both methods of retrieving the Gurobi package, or move entirely to supporting the manual download.

**Comment by jamiesnape** [comment]
> Why would they have different hashes? If you download Gurobi manually, per the new instructions, do you get the same hash that I do?

Yes

> I feel like since the installation instructions changed we should either support both methods of retrieving the Gurobi package, or move entirely to supporting the manual download.

We only support the manual download. It is less a case of where and how we downloaded the package, than when. We have been using this package for more than six months.

**Comment by jamiesnape** [comment]
(though the timestamp is  August 17, 2015 on 6.0.5 and October 9, 2015 on 6.0.5a)

**Comment by jamiesnape** [comment]
@pvarin Can you update this PR, replacing the instances of `gurobi6.0.5a_mac64.pkg` with `gurobi6.0.5_mac64.pkg`?

**Comment by pvarin** [comment]
Sure, thing. I also modified my PR to also include the hash for `gurobi6.0.5a_mac64.pkg` in case you wanted to keep it, but I can change it back.

**Comment by jamiesnape** [comment]
It is good to support both hashes for now.

**Comment by jamiesnape** [comment]
Sorry, you will need to rebase also.

**Comment by jamiesnape** [comment]
PTAL @david-german-tri.

**Comment by david-german-tri** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/gurobi/16)*

**Comment by jamiesnape** [comment]
I will update the SHA in drake.

**Comment by jamiesnape** [comment]
RobotLocomotion/drake#4228

**Pull request merged**
